### ISSUE TITLE
Blink same error when is it gonna get fixed?

### ISSUE THREAD

**Issue by burrneuro** [plaperdr/blink-docker#16]
home@root:~/blink-docker# python3 run.py
Traceback (most recent call last):
File "run.py", line 208, in
main()
File "run.py", line 142, in main
checkInstallation()
File "run.py", line 38, in checkInstallation
generateLibrairies()
File "run.py", line 54, in generateLibrairies
fedKernel = re.search("kernel-(.{1,20}"+fedoraName+")((?!testing).)*?stable",str(fedSource)).group(1)+".x86_64"
AttributeError: 'NoneType' object has no attribute 'group'

I tried ubuntu 16.04, 18.04, fedora and still can't get it to run.

**Comment by burrneuro** [comment]
nvm, fixed it.

**Comment by rolki-png** [comment]
Would be great if you write down how you fixed it! Thanks
